import { useState, useEffect, useCallback } from 'react';
import { FlaskConical } from 'lucide-react';
import { apiFetch } from '../api';
import SessionTable from './SessionTable';

export default function Dashboard({ onSelectSession, systemMode, liveFlows = [] }) {
  const [sessions, setSessions] = useState([]);
  const [stats, setStats] = useState({});
  const [alertStats, setAlertStats] = useState({});
  const [loading, setLoading] = useState(true);
  const [simBannerDismissed, setSimBannerDismissed] = useState(false);
  const [sortBy, setSortBy] = useState('last_seen');
  const [dashboardTab, setDashboardTab] = useState('sessions'); // 'sessions' | 'live_flows'

  // "Active" should mean currently active, not "ever seen this cycle" —
  // a session idle for more than this is no longer shown here (it's still
  // in the DB and fully visible in Reports' full audit, just not this view).
  const ACTIVE_WINDOW_SECONDS = 300;

  const refresh = useCallback(() => {
    const srcParam = systemMode === 'live' ? '&source=live' : '';
    Promise.all([
      apiFetch(`/sessions?limit=100&sort_by=${sortBy}&active_within_seconds=${ACTIVE_WINDOW_SECONDS}${srcParam}`),
      apiFetch('/dashboard/stats'),
      apiFetch('/alerts/stats'),
    ]).then(([s, st, as]) => {
      setSessions(s);
      setStats(st);
      setAlertStats(as);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [sortBy, systemMode]);

  useEffect(() => {
    refresh();
    const iv = setInterval(refresh, 3000);
    return () => clearInterval(iv);
  }, [refresh]);

  return (
    <>
      {/* §7 — Simulation banner (BUG FIX: only show in simulated mode) */}
      {systemMode === 'simulated' && stats.has_simulated_data && !simBannerDismissed && (
        <div style={{
          background: 'linear-gradient(90deg, rgba(230,126,34,0.12), rgba(230,126,34,0.06))',
          border: '1px solid var(--accent)',
          borderRadius: 'var(--radius)',
          padding: 'var(--sp-2) var(--sp-4)',
          marginBottom: 'var(--sp-3)',
          display: 'flex', alignItems: 'center', gap: 'var(--sp-3)',
        }}>
          <FlaskConical size={13} color="var(--accent)"/>
          <span className="mono" style={{ fontSize: '0.67rem', color: 'var(--accent)', flex: 1 }}>
            SIMULATION DATA ACTIVE — synthetic flows generated by <code>traffic_simulator.py</code> are present.
          </span>
          <button className="btn btn-sm" onClick={() => setSimBannerDismissed(true)} style={{ fontSize: '0.6rem' }}>DISMISS</button>
        </div>
      )}

      {/* Stats cards */}
      <div className="stats-bar">
        <div className="stat-card">
          <div className="stat-card-label">TOTAL_SESSIONS</div>
          <div className="stat-card-value">{stats.total_sessions || 0}</div>
        </div>
        <div className="stat-card">
          <div className="stat-card-label">FLOWS_INGESTED</div>
          <div className="stat-card-value">{stats.total_flows || 0}</div>
        </div>
        <div className="stat-card">
          <div className="stat-card-label">AT_RISK</div>
          <div className="stat-card-value" style={{ color: (stats.at_risk_sessions || 0) > 0 ? 'var(--severity-critical)' : undefined }}>
            {stats.at_risk_sessions || 0}
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-card-label">UNACK_ALERTS</div>
          <div className="stat-card-value" style={{ color: (alertStats.unacknowledged || 0) > 0 ? 'var(--severity-high)' : undefined }}>
            {alertStats.unacknowledged || 0}
          </div>
        </div>
        {stats.direction_breakdown && (
          <div className="stat-card">
            <div className="stat-card-label">INBOUND (RX)</div>
            <div className="stat-card-value" style={{ color: 'var(--severity-high)', fontSize: '1rem' }}>
              {stats.direction_breakdown.inbound || 0}
            </div>
          </div>
        )}
        {stats.direction_breakdown && (
          <div className="stat-card">
            <div className="stat-card-label">OUTBOUND (TX)</div>
            <div className="stat-card-value" style={{ color: 'var(--accent)', fontSize: '1rem' }}>
              {stats.direction_breakdown.outbound || 0}
            </div>
          </div>
        )}
      </div>

      {/* View switcher and mode indication */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 'var(--sp-2)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-3)' }}>
          <div className="tab-group">
            <button
              className={`tab-btn ${dashboardTab === 'sessions' ? 'active' : ''}`}
              onClick={() => setDashboardTab('sessions')}
            >
              ACTIVE SESSIONS ({sessions.length})
            </button>
            <button
              className={`tab-btn ${dashboardTab === 'live_flows' ? 'active' : ''}`}
              onClick={() => setDashboardTab('live_flows')}
            >
              REAL-TIME FLOWS ({liveFlows.length})
            </button>
          </div>
        </div>

        {/* Operating mode badge */}
        <div style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: 6,
          padding: '3px 10px',
          borderRadius: 'var(--radius)',
          border: `1px solid ${systemMode === 'live' ? 'rgba(39, 174, 96, 0.4)' : 'rgba(230, 126, 34, 0.4)'}`,
          background: systemMode === 'live' ? 'rgba(39, 174, 96, 0.08)' : 'rgba(230, 126, 34, 0.08)',
          fontSize: '0.67rem',
          fontWeight: 700,
          letterSpacing: '0.04em',
          color: systemMode === 'live' ? '#27ae60' : '#e67e22',
        }}>
          <span style={{
            width: 7,
            height: 7,
            borderRadius: '50%',
            background: systemMode === 'live' ? '#27ae60' : '#e67e22',
            boxShadow: systemMode === 'live' ? '0 0 6px #27ae60' : '0 0 6px #e67e22',
          }}/>
          {systemMode === 'live' ? 'MODE: LIVE ONLY' : 'MODE: SIMULATION'}
        </div>
      </div>

      {/* Delegated Session / Real-Time Flow Table */}
      <SessionTable
        sessions={sessions}
        loading={loading}
        onSelectSession={onSelectSession}
        sortBy={sortBy}
        setSortBy={setSortBy}
        dashboardTab={dashboardTab}
        liveFlows={liveFlows}
      />
    </>
  );
}
